package com.guild.services.repository;

import com.guild.core.database.DatabaseManager;
import com.guild.core.time.TimeProvider;
import com.guild.models.GuildRelation;
import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import java.util.UUID;
import java.util.logging.Logger;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

class GuildRelationRepositoryTest {

    private HikariDataSource dataSource;
    private GuildRelationRepository repository;

    private static final UUID INITIATOR_UUID = UUID.fromString("cccccccc-cccc-cccc-cccc-cccccccccccc");

    @BeforeEach
    void setUp() throws Exception {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:h2:mem:guild_relation_repo_" + UUID.randomUUID() + ";MODE=MySQL;DB_CLOSE_DELAY=-1");
        config.setMaximumPoolSize(2);
        dataSource = new HikariDataSource(config);

        try (Connection conn = dataSource.getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute("""
                    CREATE TABLE guild_relations (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        guild1_id INT NOT NULL,
                        guild2_id INT NOT NULL,
                        guild1_name VARCHAR(64) NOT NULL,
                        guild2_name VARCHAR(64) NOT NULL,
                        relation_type VARCHAR(16) NOT NULL,
                        status VARCHAR(16) DEFAULT 'PENDING',
                        initiator_uuid VARCHAR(36) NOT NULL,
                        initiator_name VARCHAR(64) NOT NULL,
                        created_at VARCHAR(32) NOT NULL,
                        updated_at VARCHAR(32) NOT NULL,
                        expires_at VARCHAR(32),
                        UNIQUE (guild1_id, guild2_id)
                    )
                    """);
        }

        DatabaseManager databaseManager = mock(DatabaseManager.class);
        when(databaseManager.getConnection()).thenAnswer(invocation -> dataSource.getConnection());
        repository = new GuildRelationRepository(databaseManager, Logger.getLogger("test"));
    }

    @AfterEach
    void tearDown() {
        if (dataSource != null) {
            dataSource.close();
        }
    }

    @Test
    void insertAndFindById() {
        assertTrue(insertRelation(1, 2, "Alpha", "Beta", GuildRelation.RelationType.ALLY));

        List<GuildRelation> relations = repository.findAllByGuildId(1);
        assertEquals(1, relations.size());

        GuildRelation relation = repository.findById(relations.get(0).getId());
        assertNotNull(relation);
        assertEquals(GuildRelation.RelationType.ALLY, relation.getType());
        assertEquals(GuildRelation.RelationStatus.PENDING, relation.getStatus());
        assertEquals("Alpha", relation.getGuild1Name());
        assertEquals("Beta", relation.getGuild2Name());
    }

    @Test
    void findByGuildPair_bidirectional() {
        assertTrue(insertRelation(10, 20, "Ten", "Twenty", GuildRelation.RelationType.ENEMY));

        GuildRelation forward = repository.findByGuildPair(10, 20);
        GuildRelation reverse = repository.findByGuildPair(20, 10);
        assertNotNull(forward);
        assertNotNull(reverse);
        assertEquals(forward.getId(), reverse.getId());
    }

    @Test
    void findAllByGuildId_ordersByCreatedAtDesc() {
        insertWithTimestamps(3, 4, "C", "D", "2024-01-01 00:00:00");
        insertWithTimestamps(3, 5, "C", "E", "2024-01-02 00:00:00");

        List<GuildRelation> relations = repository.findAllByGuildId(3);
        assertEquals(2, relations.size());
        assertEquals("E", relations.get(0).getGuild2Name());
    }

    @Test
    void updateStatus() {
        assertTrue(insertRelation(6, 7, "Six", "Seven", GuildRelation.RelationType.TRUCE));
        int relationId = repository.findByGuildPair(6, 7).getId();

        assertTrue(repository.updateStatus(relationId, GuildRelation.RelationStatus.ACTIVE, now()));

        GuildRelation updated = repository.findById(relationId);
        assertEquals(GuildRelation.RelationStatus.ACTIVE, updated.getStatus());
    }

    @Test
    void deleteById() {
        assertTrue(insertRelation(8, 9, "Eight", "Nine", GuildRelation.RelationType.WAR));
        int relationId = repository.findByGuildPair(8, 9).getId();

        assertTrue(repository.deleteById(relationId));
        assertNull(repository.findById(relationId));
    }

    @Test
    void insertReturnsFalseWhenDuplicatePair() {
        assertTrue(insertRelation(11, 12, "Eleven", "Twelve", GuildRelation.RelationType.ALLY));
        assertFalse(insertRelation(11, 12, "Eleven", "Twelve", GuildRelation.RelationType.ENEMY));
    }

    @Test
    void findByGuildPairReturnsNullWhenMissing() {
        assertNull(repository.findByGuildPair(99, 100));
    }

    private boolean insertRelation(int guild1Id, int guild2Id, String guild1Name, String guild2Name,
                                   GuildRelation.RelationType type) {
        return repository.insert(guild1Id, guild2Id, guild1Name, guild2Name, type,
                INITIATOR_UUID, "Initiator", TimeProvider.plusDaysString(7));
    }

    private void insertWithTimestamps(int guild1Id, int guild2Id, String guild1Name, String guild2Name,
                                      String createdAt) {
        try (Connection conn = dataSource.getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute(String.format("""
                    INSERT INTO guild_relations (guild1_id, guild2_id, guild1_name, guild2_name,
                        relation_type, status, initiator_uuid, initiator_name, created_at, updated_at, expires_at)
                    VALUES (%d, %d, '%s', '%s', 'ALLY', 'PENDING', '%s', 'Initiator', '%s', '%s', '%s')
                    """, guild1Id, guild2Id, guild1Name, guild2Name, INITIATOR_UUID, createdAt, createdAt,
                    TimeProvider.plusDaysString(7)));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    private static String now() {
        return TimeProvider.nowString();
    }
}
