package com.guild.services.repository;

import com.guild.core.database.DatabaseManager;
import com.guild.core.time.TimeProvider;
import com.guild.models.GuildLog;
import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import java.util.UUID;
import java.util.logging.Logger;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

class GuildLogRepositoryTest {

    private HikariDataSource dataSource;
    private GuildLogRepository repository;

    @BeforeEach
    void setUp() throws Exception {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:h2:mem:guild_log_repo_" + UUID.randomUUID() + ";MODE=MySQL;DB_CLOSE_DELAY=-1");
        config.setMaximumPoolSize(2);
        dataSource = new HikariDataSource(config);

        try (Connection conn = dataSource.getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute("""
                    CREATE TABLE guild_logs (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        guild_id INT NOT NULL,
                        guild_name VARCHAR(64) NOT NULL,
                        player_uuid VARCHAR(36) NOT NULL,
                        player_name VARCHAR(64) NOT NULL,
                        log_type VARCHAR(32) NOT NULL,
                        description VARCHAR(256),
                        details VARCHAR(512),
                        created_at VARCHAR(32) NOT NULL
                    )
                    """);
        }

        DatabaseManager databaseManager = mock(DatabaseManager.class);
        when(databaseManager.getConnection()).thenAnswer(invocation -> dataSource.getConnection());
        repository = new GuildLogRepository(databaseManager, Logger.getLogger("test"));
    }

    @AfterEach
    void tearDown() {
        if (dataSource != null) {
            dataSource.close();
        }
    }

    @Test
    void insertFindAndCount() {
        assertTrue(repository.insert(1, "Alpha", "uuid-1", "PlayerOne",
                GuildLog.LogType.GUILD_CREATED, "Created", "details", TimeProvider.nowString()));

        assertEquals(1, repository.countByGuildId(1));
        List<GuildLog> logs = repository.findByGuildId(1, 10, 0);
        assertEquals(1, logs.size());
        assertEquals(GuildLog.LogType.GUILD_CREATED, logs.get(0).getLogType());
    }

    @Test
    void deleteOlderThan() {
        repository.insert(2, "Beta", "uuid-2", "PlayerTwo",
                GuildLog.LogType.MEMBER_JOINED, "Join", "details", "2020-01-01 00:00:00");
        repository.insert(2, "Beta", "uuid-3", "PlayerThree",
                GuildLog.LogType.MEMBER_JOINED, "Join", "details", TimeProvider.nowString());

        assertTrue(repository.deleteOlderThan("2024-01-01 00:00:00") >= 1);
        assertEquals(1, repository.countByGuildId(2));
    }
}
