package com.guild.services.repository;

import com.guild.core.database.DatabaseManager;
import com.guild.core.time.TimeProvider;
import com.guild.models.GuildMember;
import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import java.util.UUID;
import java.util.logging.Logger;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

class GuildMemberRepositoryTest {

    private HikariDataSource dataSource;
    private GuildMemberRepository repository;

    private static final UUID LEADER_UUID = UUID.fromString("11111111-1111-1111-1111-111111111111");
    private static final UUID MEMBER_UUID = UUID.fromString("22222222-2222-2222-2222-222222222222");
    private static final UUID OFFICER_UUID = UUID.fromString("33333333-3333-3333-3333-333333333333");

    @BeforeEach
    void setUp() throws Exception {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:h2:mem:guild_member_repo_" + UUID.randomUUID() + ";MODE=MySQL;DB_CLOSE_DELAY=-1");
        config.setMaximumPoolSize(2);
        dataSource = new HikariDataSource(config);

        try (Connection conn = dataSource.getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute("""
                    CREATE TABLE guild_members (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        guild_id INT NOT NULL,
                        player_uuid VARCHAR(36) NOT NULL UNIQUE,
                        player_name VARCHAR(64) NOT NULL,
                        role VARCHAR(16) NOT NULL,
                        joined_at VARCHAR(32) NOT NULL
                    )
                    """);
        }

        DatabaseManager databaseManager = mock(DatabaseManager.class);
        when(databaseManager.getConnection()).thenAnswer(invocation -> dataSource.getConnection());
        repository = new GuildMemberRepository(databaseManager, Logger.getLogger("test"));
    }

    @AfterEach
    void tearDown() {
        if (dataSource != null) {
            dataSource.close();
        }
    }

    @Test
    void insertAndFindByPlayerUuid() {
        assertTrue(repository.insert(1, MEMBER_UUID, "MemberOne", GuildMember.Role.MEMBER, TimeProvider.nowString()));

        GuildMember found = repository.findByPlayerUuidAsync(MEMBER_UUID).join();
        assertNotNull(found);
        assertEquals(1, found.getGuildId());
        assertEquals("MemberOne", found.getPlayerName());
        assertEquals(GuildMember.Role.MEMBER, found.getRole());
    }

    @Test
    void findByGuildAndPlayerUuid() {
        repository.insert(7, OFFICER_UUID, "Officer", GuildMember.Role.OFFICER, TimeProvider.nowString());

        GuildMember found = repository.findByGuildAndPlayerUuidAsync(7, OFFICER_UUID).join();
        assertNotNull(found);
        assertEquals(GuildMember.Role.OFFICER, found.getRole());

        assertNull(repository.findByGuildAndPlayerUuidAsync(8, OFFICER_UUID).join());
    }

    @Test
    void countAndFindAllByGuildId() {
        repository.insert(2, LEADER_UUID, "Leader", GuildMember.Role.LEADER, TimeProvider.nowString());
        repository.insert(2, MEMBER_UUID, "MemberOne", GuildMember.Role.MEMBER, TimeProvider.nowString());

        assertEquals(2, repository.countByGuildIdAsync(2).join());

        List<GuildMember> members = repository.findAllByGuildIdAsync(2).join();
        assertEquals(2, members.size());
    }

    @Test
    void updateRole_promoteAndDemote() {
        repository.insert(3, MEMBER_UUID, "MemberOne", GuildMember.Role.MEMBER, TimeProvider.nowString());

        assertTrue(repository.updateRole(MEMBER_UUID, 3, GuildMember.Role.OFFICER));
        assertEquals(GuildMember.Role.OFFICER,
                repository.findByPlayerUuidAsync(MEMBER_UUID).join().getRole());

        assertTrue(repository.updateRole(MEMBER_UUID, 3, GuildMember.Role.MEMBER));
        assertEquals(GuildMember.Role.MEMBER,
                repository.findByPlayerUuidAsync(MEMBER_UUID).join().getRole());
    }

    @Test
    void deleteByPlayerUuid() {
        repository.insert(4, MEMBER_UUID, "MemberOne", GuildMember.Role.MEMBER, TimeProvider.nowString());

        assertTrue(repository.deleteByPlayerUuid(MEMBER_UUID));
        assertNull(repository.findByPlayerUuidAsync(MEMBER_UUID).join());
        assertEquals(0, repository.countByGuildIdAsync(4).join());
    }

    @Test
    void leadershipTransferMemberRoles() throws Exception {
        repository.insert(5, LEADER_UUID, "Leader", GuildMember.Role.LEADER, TimeProvider.nowString());
        repository.insert(5, MEMBER_UUID, "MemberOne", GuildMember.Role.MEMBER, TimeProvider.nowString());

        try (Connection conn = dataSource.getConnection()) {
            conn.setAutoCommit(false);
            repository.demoteLeaderToMember(conn, 5, LEADER_UUID);
            int promoted = repository.promoteMemberToLeader(conn, 5, MEMBER_UUID);
            conn.commit();
            assertTrue(promoted > 0);
        }

        assertEquals(GuildMember.Role.MEMBER,
                repository.findByPlayerUuidAsync(LEADER_UUID).join().getRole());
        assertEquals(GuildMember.Role.LEADER,
                repository.findByPlayerUuidAsync(MEMBER_UUID).join().getRole());
    }

    @Test
    void deleteAllByGuildId() throws Exception {
        repository.insert(6, LEADER_UUID, "Leader", GuildMember.Role.LEADER, TimeProvider.nowString());
        repository.insert(6, MEMBER_UUID, "MemberOne", GuildMember.Role.MEMBER, TimeProvider.nowString());

        try (Connection conn = dataSource.getConnection()) {
            assertTrue(repository.deleteAllByGuildId(conn, 6) >= 2);
        }

        assertEquals(0, repository.countByGuildIdAsync(6).join());
    }

    @Test
    void leaderRoleCannotBeSetViaDirectUpdateWithoutBusinessRules() {
        // Repository 层仅负责写库；业务规则（不可直接设 LEADER）由 GuildService 校验
        repository.insert(8, MEMBER_UUID, "MemberOne", GuildMember.Role.MEMBER, TimeProvider.nowString());
        assertTrue(repository.updateRoleByPlayerUuid(MEMBER_UUID, GuildMember.Role.LEADER));
        assertEquals(GuildMember.Role.LEADER,
                repository.findByPlayerUuidAsync(MEMBER_UUID).join().getRole());
    }

    @Test
    void insertReturnsFalseWhenDuplicateUuid() {
        assertTrue(repository.insert(9, MEMBER_UUID, "MemberOne", GuildMember.Role.MEMBER, TimeProvider.nowString()));
        assertFalse(repository.insert(9, MEMBER_UUID, "MemberDup", GuildMember.Role.MEMBER, TimeProvider.nowString()));
    }
}
