package com.guild.services.repository;

import com.guild.core.database.DatabaseManager;
import com.guild.core.time.TimeProvider;
import com.guild.models.Guild;
import com.guild.models.GuildMember;
import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import java.util.UUID;
import java.util.logging.Logger;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

class GuildRepositoryTest {

    private HikariDataSource dataSource;
    private GuildRepository repository;
    private GuildMemberRepository memberRepository;

    private static final UUID LEADER_UUID = UUID.fromString("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa");
    private static final UUID MEMBER_UUID = UUID.fromString("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb");

    @BeforeEach
    void setUp() throws Exception {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:h2:mem:guild_repo_" + UUID.randomUUID() + ";MODE=MySQL;DB_CLOSE_DELAY=-1");
        config.setMaximumPoolSize(2);
        dataSource = new HikariDataSource(config);

        try (Connection conn = dataSource.getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute("""
                    CREATE TABLE guilds (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(64) NOT NULL UNIQUE,
                        tag VARCHAR(16) UNIQUE,
                        description VARCHAR(512),
                        leader_uuid VARCHAR(36) NOT NULL,
                        leader_name VARCHAR(64) NOT NULL,
                        home_world VARCHAR(64),
                        home_x DOUBLE,
                        home_y DOUBLE,
                        home_z DOUBLE,
                        home_yaw REAL,
                        home_pitch REAL,
                        balance DOUBLE DEFAULT 0.0,
                        level INT DEFAULT 1,
                        peak_level INT DEFAULT 1,
                        max_members INT DEFAULT 6,
                        frozen BOOLEAN DEFAULT FALSE,
                        created_at VARCHAR(32) NOT NULL,
                        updated_at VARCHAR(32) NOT NULL
                    )
                    """);
            stmt.execute("""
                    CREATE TABLE guild_members (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        guild_id INT NOT NULL,
                        player_uuid VARCHAR(36) NOT NULL UNIQUE,
                        player_name VARCHAR(64) NOT NULL,
                        role VARCHAR(16) NOT NULL,
                        joined_at VARCHAR(32) NOT NULL
                    )
                    """);
        }

        DatabaseManager databaseManager = mock(DatabaseManager.class);
        when(databaseManager.getConnection()).thenAnswer(invocation -> dataSource.getConnection());
        Logger logger = Logger.getLogger("test");
        repository = new GuildRepository(databaseManager, logger);
        memberRepository = new GuildMemberRepository(databaseManager, logger);
    }

    @AfterEach
    void tearDown() {
        if (dataSource != null) {
            dataSource.close();
        }
    }

    @Test
    void insertAndFindById() {
        int guildId = repository.insert("Alpha", "A", "desc", LEADER_UUID, "Leader", now(), now());
        assertTrue(guildId > 0);

        Guild guild = repository.findById(guildId);
        assertNotNull(guild);
        assertEquals("Alpha", guild.getName());
        assertEquals("A", guild.getTag());
        assertEquals(LEADER_UUID, guild.getLeaderUuid());
        assertEquals(1, guild.getLevel());
        assertEquals(0.0, guild.getBalance());
    }

    @Test
    void findByNameAndTag() {
        int guildId = repository.insert("Beta", "B", "beta", LEADER_UUID, "Leader", now(), now());
        assertTrue(guildId > 0);

        assertEquals(guildId, repository.findByName("Beta").getId());
        assertEquals(guildId, repository.findByTag("B").getId());
        assertNull(repository.findByName("Missing"));
    }

    @Test
    void findByPlayerUuid() {
        int guildId = repository.insert("Gamma", "G", "gamma", LEADER_UUID, "Leader", now(), now());
        memberRepository.insert(guildId, MEMBER_UUID, "Member", GuildMember.Role.MEMBER, now());

        Guild guild = repository.findByPlayerUuid(MEMBER_UUID);
        assertNotNull(guild);
        assertEquals("Gamma", guild.getName());
    }

    @Test
    void findAllOrdersByCreatedAtDesc() {
        repository.insert("First", "F1", "one", LEADER_UUID, "Leader", "2024-01-01 00:00:00", "2024-01-01 00:00:00");
        repository.insert("Second", "F2", "two", LEADER_UUID, "Leader", "2024-01-02 00:00:00", "2024-01-02 00:00:00");

        List<Guild> all = repository.findAll();
        assertEquals(2, all.size());
        assertEquals("Second", all.get(0).getName());
    }

    @Test
    void updateInfoAndDescription() {
        int guildId = repository.insert("Delta", "D", "old", LEADER_UUID, "Leader", now(), now());

        assertTrue(repository.updateInfo(guildId, "DeltaNew", "DN", "new desc", now()));
        assertTrue(repository.updateDescription(guildId, "desc only"));

        Guild guild = repository.findById(guildId);
        assertEquals("DeltaNew", guild.getName());
        assertEquals("DN", guild.getTag());
        assertEquals("desc only", guild.getDescription());
    }

    @Test
    void updateBalanceAndLevel() {
        int guildId = repository.insert("Echo", "E", "echo", LEADER_UUID, "Leader", now(), now());

        assertTrue(repository.updateBalance(guildId, 1234.5, now()));
        assertTrue(repository.updateLevel(guildId, 3));

        Guild guild = repository.findById(guildId);
        assertEquals(1234.5, guild.getBalance());
        assertEquals(3, guild.getLevel());
        assertEquals(3, guild.getPeakLevel());
    }

    @Test
    void updateLevelMaxMembersAndPeak_keepsHigherPeak() {
        int guildId = repository.insert("Foxtrot", "F", "fox", LEADER_UUID, "Leader", now(), now());
        assertTrue(repository.updateLevel(guildId, 5));

        assertTrue(repository.updateLevelMaxMembersAndPeak(guildId, 3, 18, now()));

        Guild guild = repository.findById(guildId);
        assertEquals(3, guild.getLevel());
        assertEquals(5, guild.getPeakLevel());
        assertEquals(18, guild.getMaxMembers());
    }

    @Test
    void updateFrozenAndHome() {
        int guildId = repository.insert("Hotel", "H", "hotel", LEADER_UUID, "Leader", now(), now());

        assertTrue(repository.updateFrozen(guildId, true));
        assertTrue(repository.updateHome(guildId, "world", 1.0, 64.0, -3.0, 90.0f, 0.0f, now()));

        Guild guild = repository.findById(guildId);
        assertTrue(guild.isFrozen());
        assertTrue(guild.hasHome());
        assertEquals("world", guild.getHomeWorld());
        assertEquals(64.0, guild.getHomeY());
    }

    @Test
    void deleteById() {
        int guildId = repository.insert("India", "I", "india", LEADER_UUID, "Leader", now(), now());
        assertTrue(repository.deleteById(guildId));
        assertNull(repository.findById(guildId));
    }

    @Test
    void insertReturnsMinusOneWhenDuplicateName() {
        assertTrue(repository.insert("Juliet", "J1", "one", LEADER_UUID, "Leader", now(), now()) > 0);
        assertEquals(-1, repository.insert("Juliet", "J2", "dup", LEADER_UUID, "Leader", now(), now()));
    }

    @Test
    void updateLeaderInTransaction() throws Exception {
        int guildId = repository.insert("Kilo", "K", "kilo", LEADER_UUID, "Leader", now(), now());
        memberRepository.insert(guildId, MEMBER_UUID, "NewLeader", GuildMember.Role.MEMBER, now());

        try (Connection conn = dataSource.getConnection()) {
            conn.setAutoCommit(false);
            assertTrue(repository.updateLeader(conn, guildId, MEMBER_UUID, "NewLeader") > 0);
            conn.commit();
        }

        Guild guild = repository.findById(guildId);
        assertEquals(MEMBER_UUID, guild.getLeaderUuid());
        assertEquals("NewLeader", guild.getLeaderName());
    }

    private static String now() {
        return TimeProvider.nowString();
    }
}
