package com.guild.module.example.territory;

import com.guild.core.database.DatabaseManager;
import com.guild.core.module.ModuleContext;
import com.guild.sdk.config.ModuleConfigSection;
import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.File;
import java.sql.Connection;
import java.sql.Statement;
import java.util.UUID;
import java.util.logging.Logger;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

class TerritoryRepositoryCrossServerTest {

    @TempDir
    File dataDir;

    private HikariDataSource dataSource;
    private TerritoryRepository repositoryA;
    private TerritoryRepository repositoryB;

    @BeforeEach
    void setUp() throws Exception {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:h2:mem:territory_" + UUID.randomUUID() + ";MODE=MySQL;DB_CLOSE_DELAY=-1");
        config.setMaximumPoolSize(4);
        dataSource = new HikariDataSource(config);

        try (Connection conn = dataSource.getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute("""
                    CREATE TABLE guild_territories (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        guild_id INT NOT NULL,
                        guild_name VARCHAR(50) NOT NULL,
                        server_id VARCHAR(64) NOT NULL,
                        world_name VARCHAR(128) NOT NULL,
                        region_id VARCHAR(64) NOT NULL,
                        min_x INT NOT NULL,
                        min_y INT NOT NULL,
                        min_z INT NOT NULL,
                        max_x INT NOT NULL,
                        max_y INT NOT NULL,
                        max_z INT NOT NULL,
                        claimed_at BIGINT NOT NULL,
                        sync_state VARCHAR(16) NOT NULL,
                        updated_at BIGINT NOT NULL,
                        UNIQUE (guild_id, server_id, world_name)
                    )
                    """);
        }

        DatabaseManager databaseManager = mock(DatabaseManager.class);
        when(databaseManager.getConnection()).thenAnswer(inv -> dataSource.getConnection());
        when(databaseManager.getDatabaseType()).thenReturn(DatabaseManager.DatabaseType.MYSQL);

        TerritorySettings settings = settingsWithCrossServer(true);

        repositoryA = new TerritoryRepository(dataDir, Logger.getAnonymousLogger(), databaseManager, settings,
                TerritoryServerIdentity.forTests("terr-server-a"));
        repositoryB = new TerritoryRepository(dataDir, Logger.getAnonymousLogger(), databaseManager, settings,
                TerritoryServerIdentity.forTests("terr-server-b"));
        repositoryA.load();
        repositoryB.load();
    }

    @AfterEach
    void tearDown() {
        if (dataSource != null) {
            dataSource.close();
        }
    }

    @Test
    void sharedDatabaseListsAllServers() {
        repositoryA.put(sample(1, "terr-server-a", "world"));
        repositoryB.put(sample(1, "terr-server-b", "world_nether"));

        repositoryA.load();
        repositoryB.load();

        assertEquals(2, repositoryA.findByGuildId(1).size());
        assertEquals(1, repositoryA.findByGuildIdLocal(1).size());
        assertEquals("terr-server-a", repositoryA.findByGuildIdLocal(1).get(0).getServerId());

        assertEquals(2, repositoryB.findByGuildId(1).size());
        assertEquals(1, repositoryB.findByGuildIdLocal(1).size());
        assertEquals("terr-server-b", repositoryB.findByGuildIdLocal(1).get(0).getServerId());
    }

    @Test
    void removeLocalDoesNotAffectRemote() {
        repositoryA.put(sample(2, "terr-server-a", "world"));
        repositoryB.put(sample(2, "terr-server-b", "world"));

        repositoryA.removeLocal(2, "world");
        repositoryA.load();
        repositoryB.load();

        assertTrue(repositoryA.findByGuildIdLocal(2).isEmpty());
        assertFalse(repositoryB.findByGuildId(2).isEmpty());
    }

    private static TerritorySettings settingsWithCrossServer(boolean enabled) {
        ModuleContext context = mock(ModuleContext.class);
        ModuleConfigSection config = mock(ModuleConfigSection.class);
        when(context.getConfig()).thenReturn(config);
        when(config.getBoolean("cross-server.enabled", true)).thenReturn(enabled);
        when(config.getString("cross-server.server-id", "")).thenReturn("");
        return new TerritorySettings(context);
    }

    private static TerritoryRecord sample(int guildId, String serverId, String world) {
        long now = System.currentTimeMillis();
        return new TerritoryRecord(
                guildId, "Guild" + guildId, TerritoryRecord.defaultRegionId(guildId), serverId, world,
                0, 0, 0, 10, 10, 10, now, TerritorySyncState.MATERIALIZED, now);
    }
}
