package com.guild.module.example.territory;

import com.guild.core.database.DatabaseManager;
import com.guild.core.module.ModuleContext;
import com.guild.sdk.config.ModuleConfigSection;
import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.File;
import java.sql.Connection;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.logging.Logger;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

class TerritoryCrossServerSyncTest {

    @TempDir
    File dataDir;

    private HikariDataSource dataSource;
    private TerritoryRepository repositoryA;
    private TerritoryRepository repositoryB;
    private TerritoryCrossServerSync syncA;
    private TerritoryCrossServerSync syncB;
    private final List<String> sentFromA = new ArrayList<>();

    @BeforeEach
    void setUp() throws Exception {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:h2:mem:territory_sync_" + UUID.randomUUID() + ";MODE=MySQL;DB_CLOSE_DELAY=-1");
        config.setMaximumPoolSize(4);
        dataSource = new HikariDataSource(config);

        try (Connection conn = dataSource.getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute("""
                    CREATE TABLE guild_territories (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        guild_id INT NOT NULL,
                        guild_name VARCHAR(50) NOT NULL,
                        server_id VARCHAR(64) NOT NULL,
                        world_name VARCHAR(128) NOT NULL,
                        region_id VARCHAR(64) NOT NULL,
                        min_x INT NOT NULL,
                        min_y INT NOT NULL,
                        min_z INT NOT NULL,
                        max_x INT NOT NULL,
                        max_y INT NOT NULL,
                        max_z INT NOT NULL,
                        claimed_at BIGINT NOT NULL,
                        sync_state VARCHAR(16) NOT NULL,
                        updated_at BIGINT NOT NULL,
                        UNIQUE (guild_id, server_id, world_name)
                    )
                    """);
        }

        DatabaseManager databaseManager = mock(DatabaseManager.class);
        when(databaseManager.getConnection()).thenAnswer(inv -> dataSource.getConnection());
        when(databaseManager.getDatabaseType()).thenReturn(DatabaseManager.DatabaseType.MYSQL);

        TerritorySettings settings = settingsWithCrossServer(true, true);

        repositoryA = new TerritoryRepository(dataDir, Logger.getAnonymousLogger(), databaseManager, settings,
                TerritoryServerIdentity.forTests("terr-server-a"));
        repositoryB = new TerritoryRepository(dataDir, Logger.getAnonymousLogger(), databaseManager, settings,
                TerritoryServerIdentity.forTests("terr-server-b"));
        repositoryA.load();
        repositoryB.load();

        syncA = new TerritoryCrossServerSync(repositoryA, settings, Logger.getAnonymousLogger(), sentFromA::add);
        syncB = new TerritoryCrossServerSync(repositoryB, settings, Logger.getAnonymousLogger(), payload -> {
        });
    }

    @AfterEach
    void tearDown() {
        if (dataSource != null) {
            dataSource.close();
        }
    }

    @Test
    void publishClaim_sendsPayloadWithRevision() {
        long now = System.currentTimeMillis();
        TerritoryRecord record = sample(5, "terr-server-a", "world", now);
        repositoryA.put(record);

        syncA.publishClaim(record);

        assertEquals(1, sentFromA.size());
        assertTrue(sentFromA.get(0).contains("\"action\":\"claim\""));
        assertTrue(sentFromA.get(0).contains("\"revision\":" + now));
    }

    @Test
    void applyRemoteClaim_updatesPeerCacheFromDatabase() {
        long revision = System.currentTimeMillis();
        TerritoryRecord record = sample(7, "terr-server-a", "world", revision);
        repositoryA.put(record);
        assertTrue(repositoryB.findByGuildId(7).isEmpty());

        String payload = """
                {"action":"claim","revision":%d,"originServerId":"terr-server-a","record":%s}
                """.formatted(revision, toJson(record));

        assertTrue(syncB.applyPayload(payload));
        assertEquals(1, repositoryB.findByGuildId(7).size());
        assertEquals("terr-server-a", repositoryB.findByGuildId(7).get(0).getServerId());
    }

    @Test
    void applyRemoteClaim_discardsStaleRevision() {
        long older = 1_000L;
        long newer = 2_000L;
        TerritoryRecord record = sample(8, "terr-server-a", "world", newer);
        repositoryA.put(record);
        repositoryB.put(record);
        repositoryB.load();

        String stalePayload = """
                {"action":"claim","revision":%d,"originServerId":"terr-server-a","record":%s}
                """.formatted(older, toJson(record.withSyncState(TerritorySyncState.MATERIALIZED, older)));

        assertFalse(syncB.applyPayload(stalePayload));
        assertEquals(newer, repositoryB.get(8, "terr-server-a", "world").orElseThrow().getUpdatedAtEpochMs());
    }

    @Test
    void applyRemoteUnclaim_removesFromPeerCache() {
        long revision = System.currentTimeMillis();
        TerritoryRecord record = sample(9, "terr-server-a", "world", revision);
        repositoryA.put(record);
        repositoryB.load();
        assertEquals(1, repositoryB.findByGuildId(9).size());

        repositoryA.remove(9, "terr-server-a", "world");

        String payload = """
                {"action":"unclaim","revision":%d,"originServerId":"terr-server-a","guildId":9,"serverId":"terr-server-a","worldName":"world"}
                """.formatted(revision);

        assertTrue(syncB.applyPayload(payload));
        assertTrue(repositoryB.findByGuildId(9).isEmpty());
    }

    @Test
    void applyRemoteGuildClear_removesAllGuildRecords() {
        long revision = System.currentTimeMillis();
        repositoryA.put(sample(10, "terr-server-a", "world", revision));
        repositoryA.put(sample(10, "terr-server-b", "world_nether", revision));
        repositoryB.load();
        assertEquals(2, repositoryB.findByGuildId(10).size());

        repositoryA.removeAllForGuild(10);

        String payload = """
                {"action":"guild-clear","revision":%d,"originServerId":"terr-server-a","guildId":10}
                """.formatted(revision);

        assertTrue(syncB.applyPayload(payload));
        assertTrue(repositoryB.findByGuildId(10).isEmpty());
    }

    @Test
    void ignoresSelfOriginServerId() {
        long revision = System.currentTimeMillis();
        TerritoryRecord record = sample(11, "terr-server-a", "world", revision);
        repositoryA.put(record);

        String payload = """
                {"action":"claim","revision":%d,"originServerId":"terr-server-a","record":%s}
                """.formatted(revision, toJson(record));

        assertFalse(syncA.applyPayload(payload));
    }

    private static TerritorySettings settingsWithCrossServer(boolean enabled, boolean broadcast) {
        ModuleContext context = mock(ModuleContext.class);
        ModuleConfigSection config = mock(ModuleConfigSection.class);
        when(context.getConfig()).thenReturn(config);
        when(config.getBoolean("cross-server.enabled", true)).thenReturn(enabled);
        when(config.getBoolean("cross-server.broadcast-events", true)).thenReturn(broadcast);
        when(config.getString("cross-server.server-id", "")).thenReturn("");
        return new TerritorySettings(context);
    }

    private static TerritoryRecord sample(int guildId, String serverId, String world, long updatedAt) {
        return new TerritoryRecord(
                guildId, "Guild" + guildId, TerritoryRecord.defaultRegionId(guildId), serverId, world,
                0, 0, 0, 10, 10, 10, updatedAt, TerritorySyncState.MATERIALIZED, updatedAt);
    }

    private static String toJson(TerritoryRecord record) {
        return new com.google.gson.Gson().toJson(record);
    }
}
